# Generated by Django 3.0 on 2022-06-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='depid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
    ]
